// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-hcKlDkrjZRCYUlEabDfNErbybPjP8Ds',
    appId: '1:337224826950:web:1a7531226595f79ff48a47',
    messagingSenderId: '337224826950',
    projectId: 'dreamenglishacademy-3efcd',
    authDomain: 'dreamenglishacademy-3efcd.firebaseapp.com',
    databaseURL:
        'https://dreamenglishacademy-3efcd-default-rtdb.firebaseio.com',
    storageBucket: 'dreamenglishacademy-3efcd.firebasestorage.app',
    measurementId: 'G-B73X6MN677',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SFtCkgJXfnZMoPWxwGcpsshDJ3IeeJ0',
    appId: '1:337224826950:android:1e14ed96fb3966bff48a47',
    messagingSenderId: '337224826950',
    projectId: 'dreamenglishacademy-3efcd',
    databaseURL:
        'https://dreamenglishacademy-3efcd-default-rtdb.firebaseio.com',
    storageBucket: 'dreamenglishacademy-3efcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzoe2owbCExWou8tX72X_UMKvWNExWEjI',
    appId: '1:337224826950:ios:af9ceafb6bdf419bf48a47',
    messagingSenderId: '337224826950',
    projectId: 'dreamenglishacademy-3efcd',
    databaseURL:
        'https://dreamenglishacademy-3efcd-default-rtdb.firebaseio.com',
    storageBucket: 'dreamenglishacademy-3efcd.firebasestorage.app',
    androidClientId:
        '337224826950-p139a8tkv1d2c8qctpnod6pshd5iselr.apps.googleusercontent.com',
    iosClientId:
        '337224826950-i1u0uv2lalacdp1hl03nl56krd859vp9.apps.googleusercontent.com',
    iosBundleId: 'com.yourbridgeschool.dreamEnglishAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzoe2owbCExWou8tX72X_UMKvWNExWEjI',
    appId: '1:337224826950:ios:af9ceafb6bdf419bf48a47',
    messagingSenderId: '337224826950',
    projectId: 'dreamenglishacademy-3efcd',
    databaseURL:
        'https://dreamenglishacademy-3efcd-default-rtdb.firebaseio.com',
    storageBucket: 'dreamenglishacademy-3efcd.firebasestorage.app',
    androidClientId:
        '337224826950-p139a8tkv1d2c8qctpnod6pshd5iselr.apps.googleusercontent.com',
    iosClientId:
        '337224826950-i1u0uv2lalacdp1hl03nl56krd859vp9.apps.googleusercontent.com',
    iosBundleId: 'com.yourbridgeschool.dreamEnglishAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-hcKlDkrjZRCYUlEabDfNErbybPjP8Ds',
    appId: '1:337224826950:web:32aabd79e82dcfb4f48a47',
    messagingSenderId: '337224826950',
    projectId: 'dreamenglishacademy-3efcd',
    authDomain: 'dreamenglishacademy-3efcd.firebaseapp.com',
    databaseURL:
        'https://dreamenglishacademy-3efcd-default-rtdb.firebaseio.com',
    storageBucket: 'dreamenglishacademy-3efcd.firebasestorage.app',
    measurementId: 'G-N9LL75Q6WY',
  );
}
